name: ⚠️ Website module report
description: Report a website module issue
title: "[bug-website module] "
body:
  - type: checkboxes
    attributes:
      label: Prerequisites
      description: To rule out invalid issues, confirm and check each one of the checkboxes.
      options:
        - label: I'm using the latest version.
          required: true
        - label: All website modules are up to date.
          required: true
        - label: I'm able to see the manga within my standard browser.
          required: true

  - type: input
    attributes:
      label: System information
      description: |
        Your operating system.
      placeholder: |
        Windows 10 22H2 x64
    validations:
      required: true

  - type: textarea
    attributes:
      label: Describe the bug
      description: |
        A clear and concise description of what the bug is. To able to localize the issue we have to able to reproduce it.
        The more detailed your information is, will help use localize the issue faster.
        **Post the website, title, and the chapter.** Or better yet, attach your downloads.db.
        If your description is to vague or there insufficient steps to reproduce the issue, we may close the issue without notice.
        Because it will only pollute the issue tracker.
    validations:
      required: true

  - type: textarea
    attributes:
      label: Log
      description: |
        Attach your log file containing the issue if available. Also attach the page source if you can. It will help us solve the issue faster.
        You can get the page source by opening the particular chapter you're unable to download from your browser with right-click > view page source.
    validations:
      required: false
